open:
  api:
    title: Alpha Code Payment Service API
    version: 1.0.0
    description: SEP project with AlphaCode Payment Service API
    serverUrl: ${OPEN_API_SERVERURL:http://localhost:8095}

springdoc:
  writer-with-order-by-keys: true
  api-docs:
    server:
      url: ${OPEN_API_SERVERURL:http://localhost:8095}
  swagger-ui:
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true

logging:
  level:
    org:
      springdoc: INFO
      springframework: INFO
      io: INFO

spring:
  devtools:
    restart:
      exclude: site/alphacode/alphacodepaymentservice/dto/**
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    publisher-confirm-type: correlated
    virtual-host: /
    listener:
      simple:
        concurrency: 2          # số thread consumer
        max-concurrency: 5
        acknowledge-mode: auto
    dynamic: true



grpc:
  client:
    alpha-course-service:
      address: static://${GRPC_COURSE_SERVICE_BASE_URL:localhost}:${GRPC_COURSE_SERVICE_PORT:50052}
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext


server:
  forward-headers-strategy: native